#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nubia/tiro

PRODUCT_COPY_FILES += \
    vendor/nubia/tiro/proprietary/vendor/etc/acdbdata/pineapple_mtp/MTP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/pineapple_mtp/MTP_acdb_cal.acdb \
    vendor/nubia/tiro/proprietary/vendor/etc/acdbdata/pineapple_mtp/MTP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/pineapple_mtp/MTP_workspaceFileXml.qwsp \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/adaptive_config/mfnr_network_denoise_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_config/mfnr_network_denoise_config.xml \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/adaptive_shutter_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_shutter_config.xml \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/adaptive_shutter_config_night.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_shutter_config_night.xml \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/adaptive_shutter_config_renwen.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/adaptive_shutter_config_renwen.xml \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/beautiful_app/preference_beautify0.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beautiful_app/preference_beautify0.json \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/beautiful_app/preference_beautify1.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beautiful_app/preference_beautify1.json \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/beautiful_app/preference_beautify2.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beautiful_app/preference_beautify2.json \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/debug/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/debug/camxoverridesettings.txt \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/dualcam_cali.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dualcam_cali.bin \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/icon/water_mark_drawable_black.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_black.argb \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/icon/water_mark_drawable_black_eng.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_black_eng.argb \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/icon/water_mark_drawable_white.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_white.argb \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/icon/water_mark_drawable_white_eng.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_white_eng.argb \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/mfnr_network_denoise_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_network_denoise_config.xml \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/mfnr_network_denoise_config_night.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_network_denoise_config_night.xml \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/mfnr_network_denoise_config_renwen.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_network_denoise_config_renwen.xml \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/mfnr_network_denoise_config_underdisplay.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_network_denoise_config_underdisplay.xml \
    vendor/nubia/tiro/proprietary/vendor/etc/camera/widelencalc_cali.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/widelencalc_cali.bin \
    vendor/nubia/tiro/proprietary/vendor/etc/libnfc-hal-st.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st.conf \
    vendor/nubia/tiro/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/json.lst \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/lanai_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_ak991x_0.json \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/lanai_aw96103_0_sar_register_a.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_aw96103_0_sar_register_a.json \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/lanai_aw96103_0_sar_register_b.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_aw96103_0_sar_register_b.json \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/lanai_aw96103_0_sar_register_c.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_aw96103_0_sar_register_c.json \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/lanai_aw9610x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_aw9610x_0.json \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/lanai_fcal_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_fcal_ak991x_0.json \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/lanai_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_lsm6dso_0.json \
    vendor/nubia/tiro/proprietary/vendor/etc/sensors/config/lanai_mtp_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_mtp_ak991x_0.json \
    vendor/nubia/tiro/proprietary/vendor/etc/st54l_conf.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st54l_conf.txt \
    vendor/nubia/tiro/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/nubia/tiro/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/nubia/tiro/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/nubia/tiro/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/nubia/tiro/proprietary/vendor/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_acf.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/aw9620x_bt_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw9620x_bt_0.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/aw9620x_bt_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw9620x_bt_1.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/aw9620x_fw_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw9620x_fw_0.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/aw9620x_fw_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw9620x_fw_1.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/aw9620x_reg_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw9620x_reg_0.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/aw9620x_reg_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw9620x_reg_1.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/nubia/tiro/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/nubia/tiro/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/nubia/tiro/proprietary/vendor/firmware/gen70900_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_zap.mbn \
    vendor/nubia/tiro/proprietary/vendor/firmware/goodix_cfg_group_9916r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group_9916r.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/goodix_firmware_9916r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_9916r.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/haptic_ram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_ram.bin \
    vendor/nubia/tiro/proprietary/vendor/firmware/ois_dw9784_tiro.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_dw9784_tiro.prog \
    vendor/nubia/tiro/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_gc02m1_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_gc02m1_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_ov16a1q_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_ov16a1q_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_ov16e1q_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_ov16e1q_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_s5kgn5sp03_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_s5kgn5sp03_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.sensormodule.zte_s5kjn1sq03_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.sensormodule.zte_s5kjn1sq03_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_gc02m1_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_gc02m1_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_ov16a1q_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_ov16a1q_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_ov16e1q_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_ov16e1q_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_s5kgn5sp03_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_s5kgn5sp03_tiro.bin \
    vendor/nubia/tiro/proprietary/vendor/lib64/camera/com.zte.tuned.zte_s5kjn1sq03_tiro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.zte.tuned.zte_s5kjn1sq03_tiro.bin

PRODUCT_PACKAGES += \
    com.qti.ois.ois_dw9784_tiro \
    com.zte.eeprom.ov16a1q_tiro \
    com.zte.eeprom.ov16e1q_tiro \
    com.zte.eeprom.s5kgn5sp03_tiro \
    com.zte.eeprom.s5kjn1sq03_tiro \
    com.zte.sensor.gc02m1_tiro \
    com.zte.sensor.ov16a1q_tiro \
    com.zte.sensor.ov16e1q_tiro \
    com.zte.sensor.s5kgn5sp03_tiro \
    com.zte.sensor.s5kjn1sq03_tiro \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.zte.node.aicud \
    com.zte.node.capturepostprocess \
    com.zte.node.capturereprocess \
    com.zte.node.capturescale \
    com.zte.node.mcxrealtimepostprocess \
    com.zte.node.realtimepostprocess \
    com.zte.node.sat \
    com.zte.node.satpostprocess \
    libcamxevainterface \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8650 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.metadataserializer \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.supres \
    com.qti.feature2.swmf \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom.sm8650 \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    fingerprint.gf95xx.default \
    libcamerapostproc \
    libcamxarcskinbeautiful \
    libcamxncsdatafactory \
    libcamxwidelencalc \
    libchifeature2 \
    libgf_hal \
    sensors.qsh \
    NubiaCamera \
    android.hardware.secure_element.xml
